name: "bloaty-action"
description: "Run Bloaty McBloatface: a size profiler for binaries."
author: "Carlos Pereira Atencio"
branding:
  color: "orange"
  icon: "wind"
inputs:
  bloaty-file-args:
    description: "Files to pass to Bloaty McBloatface"
    required: true
  bloaty-additional-args:
    description: "Additional arguments to pass to Bloaty McBloatface"
    required: true
  output-to-summary:
    description: "Add the Bloaty output to the GitHub Actions Job Summary"
    required: false
    default: false
  summary-title:
    description: "Title on top of the Bloaty output in the GitHub Actions Job Summary"
    required: false
    default: "bloaty output"
  action-verbose:
    description: "Print to log additional info from the action process (not bloaty itself)"
    required: false
    default: false
outputs:
  bloaty-output:
    description: "The output from Bloaty McBloatface"
  bloaty-output-encoded:
    description: "bloaty output in a string with escaped characters (so you'll get things like \\n)"
  bloaty-summary-map:
    description: |
      "JSON object, which contains the following members:"
      "file-percentage: Total percentage by which the total file size increased/decreased in diff mode. Otherwise always 100%"
      "file-absolute: Total absolute value by which the total file size increased/decreased in diff mode. Otherwise the total file size"
      "vm-percentage: Total percentage by which the total VM size increased/decreased in diff mode. Otherwise always 100%"
      "vm-absolute: Total absolute value by which the total VM size increased/decreased in diff mode. Otherwise the total VM size"
runs:
  using: docker
  # For testing we can build the Docker file by uncommenting switching this line
  image: docker-action/Dockerfile
  #image: docker://ghcr.io/carlosperate/bloaty-action:latest
  args:
    - "--bloaty-file-args ${{ inputs.bloaty-file-args }}"
    - "--bloaty-additional-args ${{ inputs.bloaty-additional-args }}"
